---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: restart auditd
  systemd:
    name: auditd
    state: restarted

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
    enabled: yes
